### ISSUE TITLE
Python 3.4 issue

### ISSUE THREAD

**Issue by lawli3t** [datamade/probablepeople#27]
is this library currently even support in 3.4? I couldnt find any informations regarding it, but found some mentions of 3.4 in the commit log, so i assumed it would be working.

Im currently trying to manually train probablepeople to recognize names, but get an error when trying to read my csv file (also happens when trying to read any of the provided ones). 

```
$ parserator label name_data/unlabeled/athletes.csv name_data/labeled/labeled.xml probablepeople
Traceback (most recent call last):
  File "/usr/local/bin/parserator", line 9, in <module>
    load_entry_point('parserator==0.4.1', 'console_scripts', 'parserator')()
  File "/usr/local/lib/python3.4/dist-packages/parserator/main.py", line 37, in dispatch
    args.func(args)
  File "/usr/local/lib/python3.4/dist-packages/parserator/main.py", line 45, in label
    manual_labeling.label(module, infile_path, outfile_path)
  File "/usr/local/lib/python3.4/dist-packages/parserator/manual_labeling.py", line 206, in label
    strings = set([row[0].decode('utf-8') for row in reader])
  File "/usr/local/lib/python3.4/dist-packages/parserator/manual_labeling.py", line 206, in <listcomp>
    strings = set([row[0].decode('utf-8') for row in reader])
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by fgregg** [comment]
probable people is 3.4 compliant, but parserator is not right now.

**Comment by lawli3t** [comment]
i see, thank you
