### ISSUE TITLE
AttributeError: 'module' object has no attribute 'TAGGER'

### ISSUE THREAD

**Issue by schmidtc** [datamade/probablepeople#38]
Trying to follow the direction in the readme to retrain the model and I get the following exception...

```
$ parserator label name_data/unlabeled/banks.csv name_data/labeled/banks_labeled.xml probablepeople
~/probablepeople/probablepeople/__init__.py:66: UserWarning: You must train the model (parserator train [traindata] [modulename]) to create the person_learned_settings.crfsuite file before you can use the parse and tag methods
  warnings.warn('You must train the model (parserator train [traindata] [modulename]) to create the %s file before you can use the parse and tag methods' % MODEL_FILES[model_type])
~/probablepeople/probablepeople/__init__.py:66: UserWarning: You must train the model (parserator train [traindata] [modulename]) to create the company_learned_settings.crfsuite file before you can use the parse and tag methods
  warnings.warn('You must train the model (parserator train [traindata] [modulename]) to create the %s file before you can use the parse and tag methods' % MODEL_FILES[model_type])
Traceback (most recent call last):
  File "~/.env/bin/parserator", line 11, in <module>
    sys.exit(dispatch())
  File "~/.env/lib/python2.7/site-packages/parserator/main.py", line 58, in dispatch
    args.func(args)
  File "~/.env/lib/python2.7/site-packages/parserator/main.py", line 79, in label
    manual_labeling.label(module, infile_path, outfile_path)
  File "~/.env/lib/python2.7/site-packages/parserator/manual_labeling.py", line 213, in label
    if module.TAGGER:
AttributeError: 'module' object has no attribute 'TAGGER'

```

Seems to be a bug related to #25

**Comment by going-cam** [comment]
running into the same issue

**Comment by going-cam** [comment]
A workaround for this is to comment out line 211, 213 & 214. This will allow you to label your csv files.

`    #if module.TAGGER:
    labeled_list, raw_strings_left = consoleLabel(strings, labels, module) 
    #else:
     #   labeled_list, raw_strings_left = naiveConsoleLabel(strings, labels, module)`
