### ISSUE TITLE
throws exception while parsing name Andre and Amanda Smith

### ISSUE THREAD

**Issue by az0** [datamade/probablepeople#42]
````
>>> import probablepeople
>>> probablepeople.tag('Andre and Amanda Smith')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\lib\site-packages\probablepeople\__init__.py", line 132, in
tag
    raise RepeatedLabelError(raw_string, parse(raw_string), label)
probablepeople.RepeatedLabelError:
ERROR: Unable to tag this string because more than one area of the string has the same label

ORIGINAL STRING:  Andre and Amanda Smith
PARSED TOKENS:    [('Andre', 'GivenName'), ('and', 'Surname'), ('Amanda', 'GivenName'), ('Smith', 'Surname')]
UNCERTAIN LABEL:  GivenName

When this error is raised, it's likely that either (1) the string is not a valid person/corporation name or (2) some tokens were labeled incorrectly

To report an error in labeling a valid name, open an issue at https://github.com/datamade/probablepeople/issues/new - it'll help us continue to improve probablepeople!

For more information, see the documentation at http://probablepeople.readthedocs.org/
````

probablepeople version 0.5.4 installed via pip
Python 2.7.11 32-bit
Microsoft Windows 7 64-bit

**Comment by jeancochrane** [comment]
Thanks for filing this @az0! I'm going to merge your other bad parse issue (#44) here:

```
RepeatedLabelError:
ERROR: Unable to tag this string because more than one area of the string has the same label

ORIGINAL STRING:  Lee Ann Womack
PARSED TOKENS:    [('Lee', 'Surname'), ('Ann', 'GivenName'), ('Womack', 'Surname')]
UNCERTAIN LABEL:  Surname

When this error is raised, it's likely that either (1) the string is not a valid person/corporation name or (2) some tokens were labeled incorrectly

To report an error in labeling a valid name, open an issue at https://github.com/datamade/probablepeople/issues/new - it'll help us continue to improve probablepeople!

For more information, see the documentation at http://probablepeople.readthedocs.org/
```

So far the list of bad parses is

```
Andre and Amanda Smith
Lee Ann Womack
```
 If you run across any more individual failing parses, feel free to drop them in this issue and we can collate them all next time we do a batch of training data. If it seems like a whole pattern is failing you can go ahead and open up a new issue to track that.
