### ISSUE TITLE
Valid person throws error

### ISSUE THREAD

**Issue by palewire** [datamade/probablepeople#62]
```>>> pp.tag("Brooke Slavik Jung", type="person")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/ben/.virtualenvs/himmel.latimes.com/local/lib/python2.7/site-packages/probablepeople/__init__.py", line 132, in tag
    raise RepeatedLabelError(raw_string, parse(raw_string), label)
RepeatedLabelError: 
ERROR: Unable to tag this string because more than one area of the string has the same label

ORIGINAL STRING:  Brooke Slavik Jung
PARSED TOKENS:    [('Brooke', 'GivenName'), ('Slavik', 'MiddleName'), ('Jung', 'Surname')]
UNCERTAIN LABEL:  GivenName

When this error is raised, it's likely that either (1) the string is not a valid person/corporation name or (2) some tokens were labeled incorrectly

To report an error in labeling a valid name, open an issue at https://github.com/datamade/probablepeople/issues/new - it'll help us continue to improve probablepeople!

For more information, see the documentation at http://probablepeople.readthedocs.org/
```

**Comment by jeancochrane** [comment]
Thanks for raising this, @palewire. I'm guessing this was in the `tag` method? Very strange error, since it doesn't seem like a label was actually repeated. I'm flagging as a bug until we can figure out what's going on.
